<?php
//CoffeeShop details

$menu = new Menu("desserts");
$menu->setName("Chocolate Mud Cake");
$menu->setPrice(3);
$menu->setId(1);
$menu->add("cakes");
$menu->setName("Vanilla Mud Cake");
$menu->setPrice(3);
$menu->setId(2);
$menu->add("cakes");
$menu->setName("Boston Cheesecake");
$menu->setPrice(3);
$menu->setId(3);
$menu->add("cakes");
$menu->setName("Pancake");
$menu->setPrice(3);
$menu->setId(4);
$menu->add("pancakes");
$menu->setName("Waffle");
$menu->setPrice(3);
$menu->setId(5);
$menu->add("waffles");
$menu->setName("Cream");
$menu->setPrice(1);
$menu->setId(6);
$menu->addOns("cakes");
$menu->setName("Fruits");
$menu->setPrice(1);
$menu->setId(7);
$menu->addOns("pancakes");
$menu->setName("Fruits");
$menu->setPrice(1);
$menu->setId(8);
$menu->addOns("waffles");

$menu->setType("drinks");
$menu->setName("Black Coffee");
$menu->setPrice(2);
$menu->setId(9);
$menu->add("coffee");
$menu->setName("Cafe Latte");
$menu->setPrice(2.50);
$menu->setId(10);
$menu->add("coffee");
$menu->setName("Coffee Mocha");
$menu->setPrice(2.50);
$menu->setId(11);
$menu->add("coffee");
$menu->setName("English Tea");
$menu->setPrice(1.50);
$menu->setId(12);
$menu->add("tea");
$menu->setName("Vanilla milkshake");
$menu->setPrice(0);
$menu->setId(13);
$menu->add("milkshake");
$menu->setName("Caramel milkshake");
$menu->setPrice(0);
$menu->setId(14);
$menu->add("milkshake");
$menu->setName("Chocolate milkshake");
$menu->setPrice(0);
$menu->setId(15);
$menu->add("milkshake");
$menu->setName("Beer");
$menu->setPrice(5);
$menu->setId(16);
$menu->add("beer");
$menu->setName("Spirits");
$menu->setPrice(5);
$menu->setId(17);
$menu->add("spirits");

$menu->setType("toys");
$menu->setName("Teddy Bear");
$menu->setPrice(7);
$menu->setId(18);
$menu->setColor("red");
$menu->add("stuffed");
$menu->setName("Teddy Bear");
$menu->setPrice(6);
$menu->setId(19);
$menu->setColor("blue");
$menu->add("stuffed");
$menu->setName("Teddy Bear");
$menu->setPrice(6);
$menu->setId(20);
$menu->setColor("orange");
$menu->add("stuffed");
$menu->setName("Giraffe");
$menu->setPrice(7);
$menu->setId(21);
$menu->add("stuffed");

$menu = $menu->getMenu();
